export const USER_DATA_REQUEST="USER_DATA_REQUEST"
export const USER_DATA_SUCCESS="USER_DATA_SUCCESS"
export const USER_DATA_ERROR="USER_DATA_ERROR"
export const USER_DELETED="USER_DELETED"
export const FIND_USER="FIND_USER"
export const UPDATE_USER="UPDATE_USER"
export const ADMIN_LOGGED="ADMIN_LOGGED"
export const ADMIN_LOGGED_ERROR="ADMIN_LOGGED_ERROR"
export const ADMIN_LOGOUT="ADMIN_LOGOUT"
export const ADMIN_LOGOUT_ERROR="ADMIN_LOGOUT_ERROR"


